config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'top#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :events do
    get :guests_index, on: :member, controller: :events
  end
  resources :users, only: [:show]
  resources :attends, only: [:create, :destroy]
  resources :joins, only: [:create, :destroy]
  resources :contacts, only: [:new, :create, :index]

  resources :groups do
    get :preview, on: :member
    resources :comments
  end
end

app/models/group.rb
class Group < ApplicationRecord
  mount_uploader :icon, ImageUploader

  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :summary, presence: true

  has_many :joins, dependent: :destroy
  has_many :users, through: :joins
  has_many :comments, dependent: :destroy

  def decide_leader(user)
    # ここのcreateはコンソールでのcreateコマンドと同じ
    joins.create(user: user, is_leader: true)
  end

  def self.identify_leader(group)
    leader_id = group.joins.find_by(is_leader: true).user_id
    User.find(leader_id)
  end

  def self.group_leader?(group, user)
    leader_id = group.joins.find_by(is_leader: true).user_id
    user.id == leader_id
  end

  def self.group_member?(group, user)
    group.users.find_by(name: user&.name).present?
  end

  def invite_member(user, group)
    if Group.group_member?(group, user)
      "#{user.name}さんは既にグループに登録済みです。"
    elsif joins.create(user: user)
      "#{user.name}さんがグループに参加しました！"
    else
      "#{user.name}さんのグループ参加が失敗しました。"
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create show edit update destroy]
  before_action :set_group, only: %i[show edit update destroy preview]
  before_action :check_group_leader, only: %i[edit update destroy]
  before_action :check_group_member, only: %i[show]

  def index
    @groups = Group.all
  end

  def show
    @joins = @group.joins.where(is_leader: false).includes(:user)
    @leader = Group.identify_leader(@group)
    @comments = @group.comments.all.includes(:user)
    @comment = @group.comments.build
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      @group.decide_leader(current_user)
      redirect_to group_path(@group), notice: "グループ「#{@group.name}」を登録しました！"
    else
      redirect_to new_group_path
    end
  end

  def edit; end

  def update
    if @group.update(group_params)
      redirect_to group_path(@group), notice: "グループ「#{@group.name}」情報を更新しました！"
    else
      render :edit
    end
  end

  def destroy
    if @group.destroy
      redirect_to user_path(id: current_user.id)
    else
      render :show
    end
  end

  def preview
    @joins = @group.joins.where(is_leader: false).includes(:user)
    @leader = Group.identify_leader(@group)
  end

  private

  def group_params
    params.require(:group).permit(:name, :summary, :icon)
  end

  def set_group
    @group = Group.find(params[:id])
  end

  # ログインユーザーがグループのリーダーであるかを確認する
  def check_group_leader
    redirect_to group_path(@group), notice: "リーダー以外は編集とか出来ません"\
    unless Group.group_leader?(@group, current_user)
  end

  # グループメンバー以外はグループ情報を見れないようにする
  def check_group_member
    redirect_to user_path(id: current_user.id), alert: "グループメンバー以外は見れません"\
    unless Group.group_member?(@group, current_user)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<% if group.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(group.errors.count, "") %>件のエラーがあります。</h2>

    <ul>
    <% group.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="container my-3">
  <%= form_with(model: group, local: true, html: { role: 'form', :id => "group_form" }) do |f| %>
    <div class="form-group">
      <%= f.label :icon %>
      <%= f.file_field :icon, class: 'form-control-file' %>
    </div>

    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, class: 'form-control', placeholder: "チーム名を入力してください（必須）" %>
    </div>

    <div class="form-group">
      <%= f.label :summary %><br />
      <%= f.text_area :summary, class: 'form-control', placeholder: "グループ概要を入力してください（必須）" %>
    </div>

    <div class="my-5">
      <%= f.submit class: 'btn btn-outline-primary' %>
    </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<h3>グループ編集</h3>

<%= render partial: 'form', locals: { group: @group } %>

app/views/groups/index.html.erb
<div class="group-index container">
  <div class="group-index__title">
    <p>グループ一覧</p>
  </div>
  <% @groups.each do |group| %>
    <div class="group-index__info">
      <%= link_to preview_group_path(group) do %>
        <div class="group-index__info__image">
          <% if group.icon.url.presence %>
            <%= image_tag group.icon.url, style: 'border: 1px solid lightgray' %>
          <% else %>
            <!-- 'no_image.png'は、assets/images内に配置 -->
            <%= image_tag 'no_image.png', style: 'border: 1px solid lightgray' %>
          <% end %>
        </div>
      <% end %>
      <div>
        <p><%= group.name %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/new.html.erb
<div class="container my-3">
  <h3>グループ新規作成</h3>
</div>

<%= render partial: 'form', locals: { group: @group } %>

app/views/groups/preview.html.erb
<div class="container">
  <div class="group-preview">
    <div class="group-preview__info">
      <div class="group-preview__info__icon-and-name">
        <div class="group-preview__info__icon">
          <% if @group.icon.url.presence %>
            <%= image_tag @group.icon.url %>
          <% else %>
            <!-- 'no_image.png'は、assets/images内に配置 -->
            <%= image_tag 'no_image.png' %>
          <% end %>
        </div>
        <div class="group-preview__info__name my-2">
          <p><%= @group.name %></p>
        </div>
        <div>
          <% unless Group.group_member?(@group, current_user) %>
            <%= form_with(url: joins_path, method: :post, local: true) do |f| %>
              <%= f.hidden_field :user_email, value: current_user&.email %>
              <%= f.hidden_field :group_id, value: @group.id %>
              <%= f.submit 'グループに参加する', class: 'btn btn-success' %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="group-preview__summary">
        <div class="group-preview__summary__leader">
          <p>リーダー</p>
          <% if @leader.icon.url.presence %>
              <%= image_tag @leader.icon.url, size: '70x70',
                                            class: 'rounded-circle border border-secondly img-responsive my-2' %>
            <% else %>
              <!-- 'no_image_man.jpeg'は、app/assets/images内に配置 -->
              <%= image_tag 'no_image_man.jpg', size: '70x70',
                                                class: 'rounded-circle border border-secondly img-responsive my-2' %>
            <% end %>
          <span class="mx-3"><%= @leader.name %></span>
        </div>
        <div class="group-preview__summary__description">
          <p>グループの説明</p>
          <p><%= @group.summary%></p>
        </div>
      </div>
    </div>
    <div class="group-preview__member">
      <p>グループメンバー（<%= @joins.count %>名）</p>
      <% @joins.each do |join| %>
        <div class="group-preview__member__description">
          <% if join.user.icon.url.presence %>
            <%= image_tag join.user.icon.url, size: '70x70',
                                          class: 'rounded-circle border border-secondly img-responsive my-2' %>
          <% else %>
            <!-- 'no_image_man.jpeg'は、app/assets/images内に配置 -->
            <%= image_tag 'no_image_man.jpg', size: '70x70',
                                              class: 'rounded-circle border border-secondly img-responsive my-2' %>
          <% end %>
          <span class="mx-2"><%= join.user.name %></span>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/groups/show.html.erb
<div class="container">
  <h3>グループページ</h3>
  <div class="card shadow img-thumbnail mx-auto" style="max-width: 70rem;">
    <% if @group.icon.url.presence %>
      <%= image_tag @group.icon.url, class: 'img-top', style: 'width: 300px ; height: auto;' %>
    <% else %>
      <!-- 'no_image.png'は、assets/images内に配置 -->
      <%= image_tag 'no_image.png', class: 'img-fluid', style: 'border: 1px solid lightgray' %>
    <% end %>
    <div class="card-body">
      <p>グループ名：<%= @group.name %></p>
      <p>リーダー：<%= @leader.name %></p>
      <p>概要：<%= @group.summary %></p>

      <p>グループメンバー</p>
      <% @joins.each do |join| %>
        <p>
          <span class="mx-2"><%= join.user.name %></span>
          <% if current_user == join.user || @leader == current_user %>
            <span><%= link_to '脱退', join_path(join), method: :delete, class: 'btn btn-danger' %></span>
          <% end %>
        </p>
      <% end %><br/>

      <p>メンバー招待</p>
      <%= form_with(url: joins_path, method: :post, local: true) do |f| %>
        <div>
          <%= f.label :user_email, 'ユーザーアドレス' %>
          <%= f.text_field :user_email, class: 'form-control' %>
          <%= f.hidden_field :group_id, value: @group.id %>
        </div>

        <div class="actions">
          <%= f.submit '招待する', class: 'btn btn-success' %>
        </div>
      <% end %><br/>

      <div>
        <p>コメント欄</p>
        <% @comments.each do |com| %>
          <p>
            <span>名前：<%= com.user.name %></span>
            <span>コメント：<%= com.text %></span>
            <span>投稿日：<%= com.updated_at.to_time %></span>
          </p>
        <% end %>
      </div>

      <%= render partial: 'comments/form', locals: { comment: @comment, group: @group } %>

      <%= link_to '一覧へ', events_path, class: 'btn btn-primary' %>
      <% if @leader.id == current_user.id %>
        <%= link_to 'グループ編集', edit_group_path(@group), class: 'btn btn-success' %>
        <%= link_to 'グループ削除', group_path(@group),
                                    method: :delete,
                                    data: { confirm: "タスク「#{@group.name}」を削除します。よろしいですか？" },
                                    class: 'btn btn-danger' %>
      <% end %>
    </div>
  </div>
</div>