config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'top#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :events do
    get :guests_index, on: :member, controller: :events
  end
  resources :users, only: [:show]
  resources :attends, only: [:create, :destroy]
  resources :joins, only: [:create, :destroy]
  resources :contacts, only: [:new, :create, :index]

  resources :groups do
    get :preview, on: :member
    resources :comments
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :icon, ImageUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google]

  validates :name, presence: true

  has_many :events, dependent: :destroy
  has_many :joins, dependent: :destroy
  has_many :groups, through: :joins, dependent: :destroy
  has_many :attends, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :comments, dependent: :destroy

  # oauth認証
  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)
    user ||= User.new(
      name: auth.info.name,
      email: auth.info.email,
      provider: auth.provider,
      uid: auth.uid,
      password: Devise.friendly_token[0, 20]
    )
    user.save
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  def google
    @user = User.find_for_google(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "google") if is_navigational_format?
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def build_resource(hash = {})
    hash[:uid] = User.create_unique_string
    super
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # ログイン後、イベントindex画面に移動する
  def after_sign_in_path_for(resource)
    events_path
  end

  # アカウント情報編集後、マイページに移動する
  def after_update_path_for(resource)
    user_path(id: current_user.id)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @groups = @user.groups.all
    @events = @user.attends.map(&:event)
    @user_planning_events = @user.events
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_apply_event?(event)
    guest_ids = event.attends.map(&:user_id)
    guest_ids.include?(current_user.id)
  end

  def user_contribute_event?(event)
    event.user.id == current_user.id
  end
end

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="container">
    <h2 class="my-3">マイページ</h2>
    <div class="row user-info py-3">
      <div class="user-info__icon col-sm-2">
        <% if @user.icon.url.presence %>
            <%= image_tag @user.icon.url, size: '100x100',
                                          class: 'rounded-circle border border-secondly img-responsive my-2' %>
          <% else %>
            <!-- 'no_image_man.jpeg'は、app/assets/images内に配置 -->
            <%= image_tag 'no_image_man.jpg', size: '100x100',
                                              class: 'rounded-circle border border-secondly img-responsive my-2' %>
        <% end %>
      </div>
      <div class="user-info__name-and-email col-sm-4 col-lg-4">
        <p class="my-3">名前：<%= @user.name %></p>
        <p class="my-3">メール：<%= @user.email %></p>
        <p><%= link_to 'プロフィール変更', edit_user_registration_path, class: 'btn btn-success' %></p>
      </div>

      <div class="user-info__group col-sm-12 col-lg-6 card p-2">
        <p>所属グループ</p>
        <div class="user-info__group-flex">
          <div class="user-info__group__index">
            <% @groups.each do |g| %>
              <div class="user-info__group__index__item">
                <%= link_to "#{g.name}", group_path(g) %>
              </div>
            <% end %>
          </div>
          <div class="user-info__group__btn">
            <%= link_to 'グループ作成', new_group_path, class: 'btn-sm btn-primary mb-3' %>
            <%= link_to '所属グループ一覧', events_path, class: 'btn-sm btn-info' %>
          </div>
        </div>
      </div>
    </div>
  </div>

<div class="container user-info__planning-event p-3">
  <h5>投稿したイベント</h5>
  <div class="row user-info__planning-event--flex">
    <% @user_planning_events.each do |event| %>
      <div class="user-info__planning-event__item col-sm-4 my-2">
        <%= link_to "#{event.name}", contacts_path(id: event.id) %>
      </div>
    <% end %>
  </div>
</div>

<%= render partial: 'events/index', locals: { events: @events }%>