config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'top#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :events do
    get :guests_index, on: :member, controller: :events
  end
  resources :users, only: [:show]
  resources :attends, only: [:create, :destroy]
  resources :joins, only: [:create, :destroy]
  resources :contacts, only: [:new, :create, :index]

  resources :groups do
    get :preview, on: :member
    resources :comments
  end
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :image, ImageUploader

  # kaminariのページネーション設定
  paginates_per 12

  validates :name, presence: true, length: { maximum: 100 }
  validates :start_at, presence: true
  validate :time_check
  with_options presence: true do
    validates :place
    validates :date
    validates :cost
    validates :capacity
  end

  belongs_to :user
  has_many :attends, dependent: :destroy
  has_many :users, through: :attends
  has_many :contacts, dependent: :destroy

  def time_check
    errors.add(:end_at, ": 開始時間より遅い終了時間は入力出来ません。") if start_at && start_at > end_at
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit destroy]
  before_action :check_contributor, only: %i[edit update destroy]

  def index
    @q = Event.all.ransack(params[:q])
    @events = @q.result(distinct: true).where('date >= ?', Date.today).order(updated_at: 'DESC').page(params[:page])
  end

  def show
    @event = Event.find(params[:id])
    @attend = Attend.find_by(user_id: current_user.id, event_id: @event.id) if current_user
    all_guest = @event.attends.all.limit(3)
    @guests = all_guest.map(&:user)
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.new(event_params)
    if @event.save
      redirect_to events_path, notice: "イベント「#{@event.name}」を登録しました！"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to events_path, notice: "イベント#{@event.name}の情報を更新しました！"
    else
      render :edit
    end
  end

  def destroy
    if @event.destroy
      redirect_to events_path, alert: "イベント#{@event.name}の情報を削除しました！"
    else
      render :index
    end
  end

  def guests_index
    @event = Event.find(params[:id])
    all_guest = @event.attends.all
    @guests = all_guest.map(&:user)
  end

  private

  def event_params
    params.require(:event).permit(:name, :place, :image, :date, :start_at, :end_at, :cost, :capacity, :link_url, :meta)
  end

  def check_contributor
    if current_user.id == Event.find(params[:id]).user.id
      @event = Event.find(params[:id])
    else
      redirect_to events_path, alert: "投稿者以外はイベントを編集、削除出来ません!"
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_app_info.html.erb
<div class="appinfo row justify-content-center">
  <div class="appinfo__event-info col-sm-8 col-lg-5 m-3">
    <div class="appinfo__title">
      <p>イベントに行ってみよう</p>
    </div>
    <div class="appinfo__event-info__description">
      <div class="event-info__bar">
        <i class="fa fa-search-plus event-info__icon"></i>
        <p class="event-info__text">イベント詳細画面から</p>
      </div>
      <div class="event-info__arrow">
        <i class="fa fa-arrow-down"></i>
      </div>
      <div class="event-info__bar">
        <i class="fa fa-arrow-circle-right event-info__icon"></i>
        <p class="event-info__text">申し込み！</p>
      </div>
    </div>
  </div>

  <div class="appinfo__group-info col-sm-8 col-lg-5 m-3">
    <div class="appinfo__title">
      <p>グループに参加しよう</p>
    </div>
    <div class="group-info__description">
      <div class="group-info__description__title-and-icon">
        <div class="group-info__description__title">
          <p>色々なグループを見て<br>参加してみよう</p>
        </div>
        <div class="group-info__user-alone">
          <i class="fa fa-user"></i>
        </div>
      </div>
      <div class="group-info__description__arrow">
        <i class="fa fa-arrow-right"></i>
      </div>
      <div class="group-info__group-icon">
        <div class="group-info__user-icon icon--normal">
          <i class="fa fa-user m-1"></i><i class="fa fa-user m-1"></i><i class="fa fa-user m-1"></i>
        </div>
        <div class="group-info__user-icon icon--secret">
          <i class="fa fa-user-secret m-1"></i><i class="fa fa-user-secret m-1"></i><i class="fa fa-user-secret m-1"></i>
        </div>
        <div class="group-info__user-icon icon--kids">
          <i class="fa fa-child m-1"></i><i class="fa fa-child m-1"></i><i class="fa fa-child m-1"></i>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<% if event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(event.errors.count, "") %>件のエラーがあります。</h2>

    <ul>
    <% event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <%= form_with(model: event, local: true, html: { role: 'form', :id => "event_form" }) do |f| %>
    <div class="form-group my-3">
      <%= f.label :image %>
      <%= image_tag(event.image.url, width: '30%', height: 'auto', style: 'object-fit: cover;') if event.image && event.image.url %>
      <%= f.file_field :image, class: 'form-control-file' %>
      <%= f.hidden_field :image_cache %>
    </div>

    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name.to_s, class: 'form-control', placeholder: "必須項目です" %>
    </div>

    <div class="form-group">
      <%= f.label :place %><br />
      <%= f.text_field :place, class: 'form-control', placeholder: "場所を入力してください（必須）" %>
    </div>

    <div class="form-group">
      <%= f.label :date %><br />
      <%= f.date_field :date, class: 'form-control', placeholder: "Please enter like => 2020-06-07" %>
    </div>

    <div class="form-group">
      <%= f.label :start_at %><br />
      <%# binding.pry %>
      <%= f.time_field :start_at, value: event.start_at&.strftime("%H:%M"), class: 'form-control cancel' %>
    </div>

    <div class="form-group">
      <%= f.label :end_at %>
      <%= f.time_field :end_at, value: event.end_at&.strftime("%H:%M"), class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :cost %><br />
      <%= f.text_field :cost, class: 'form-control', placeholder: "参加費を円単位、半角数字で入力してください（必須）" %>
    </div>

    <div class="form-group">
      <%= f.label :capacity %><br />
      <%= f.text_field :capacity, class: 'form-control', placeholder: "参加可能人数を半角数字で入力してください（必須）" %>
    </div>

    <div class="form-group">
      <%= f.label :link_url%>
      <%= f.text_field :link_url, class: 'form-control', placeholder: "参照するurlがあれば入力してください" %>
    </div>

    <div class="form-group">
      <%= f.label :meta %>
      <%= f.text_area :meta, class: 'form-control', placeholder: "備考欄" %>
    </div>

    <div class="my-5">
      <%= f.submit class: 'btn btn-outline-primary' %>
    </div>
  <% end %>

  <%= link_to '一覧へ', events_path, class: 'btn btn-primary' %>
</div>

app/views/events/_index.html.erb
<div class="container user-apply-event px-1 py-3 mt-3">
  <h5 class="ml-3 mb-3">参加を申し込んだイベント</h5>

  <div class="user-apply-event__index" >
    <% events.each do |event| %>
      <div class="card img-thumbnail mx-auto user-apply-event__index__item">
        <% if event.image.url.presence %>
          <%= image_tag event.image.url, style: 'border: 1px solid lightgray' %>
        <% else %>
          <!-- 'no_image.png'は、assets/images内に配置 -->
          <%= image_tag 'no_image.png', style: 'border: 1px solid lightgray' %>
        <% end %>
        <div class="card-body">
          <p class="card-title"><%= event.name %></p>
          <p class="card-subtitle text-muted">開催日:<%= event.date %></p>
          <%= link_to '詳細', event_path(event), class: 'btn-sm btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container my-3">
  <h3>イベント編集</h3>
</div>

<%= render partial: 'form', locals: { event: @event } %>

app/views/events/guests_index.html.erb
<div class="container my-5">
  <p>現在の参加者一覧</p>
  <% if @guests.present? %>
    <% @guests.each do |g| %>
      <div class="card container">
        <div class="card-body"><%= g.name %>さん</div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="container my-3">
  <div class="text-center index-event__title">
    <p>イベント一覧</p>
  </div>

  <div class="text-center my-3">
    <%= link_to 'イベント登録', new_event_path, class: 'button button-event' if current_user %>
  </div>
  <div class="index_events" >
    <% @events.each do |event| %>
      <div class="card img-thumbnail mx-auto caption">
        <% if event.image.url.presence %>
          <%= image_tag event.image.url, style: 'border: 1px solid lightgray' %>
        <% else %>
          <!-- 'no_image.png'は、assets/images内に配置 -->
          <%= image_tag 'no_image.png', style: 'border: 1px solid lightgray' %>
        <% end %>
        <div class="card-body">
          <p class="card-title"><%= event.name %></p>
          <p class="card-subtitle text-muted">開催日:<%= event.date %></p>
          <%= link_to '詳細', event_path(event), class: 'btn btn-primary btn-sm float-right' %>
        </div>
      </div>
    <% end %>
  </div>

    <div class="my-3">
      <%= paginate @events %>
      <%= page_entries_info @events %>
    </div>
</div>

app/views/events/new.html.erb
<h1>イベント新規登録</h1>

<%= render partial: 'form', locals: { event: @event } %>

app/views/events/show.html.erb
<div class="container my-3">
  <h3 class="my-3">イベント詳細</h3>
  <div class="card shadow mx-auto" style="max-width: 70rem;">
    <div class="card-header">
      <strong><span>投稿者：<%= @event.user.name %></span></strong>
      <%= link_to 'お問い合わせ', new_contact_path(event_id: @event.id),
                                                  class: 'btn btn-info float-right' if current_user %>
    </div>

    <div class="card-body">
      <div class="container">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">イベント名：<strong><%= @event.name %></strong></li>
          <li class="list-group-item">開催場所：<%= @event.place %></li>
          <li class="list-group-item">日時：<%= @event.date %> 、開始時間：<%= "#{@event.start_at.strftime("%H:%M")}" %>
          、終了時間：<%= @event.end_at.presence ?  "#{@event.end_at&.strftime("%H:%M")}" : '未設定' %></li>
          <li class="list-group-item">参加費用：<%= "#{@event.cost}円" %></li>
          <li class="list-group-item">url：<a href="<%= "#{@event.link_url}" %>"><%= "#{@event.link_url}" %></a></li>
          <li class="list-group-item">概要：<%= @event.meta %></li>
        </ul>
      </div>

      <div class="container mt-5">
        <!-- イベントへの参加（attend create）ボタン -->
        <!-- ログインしていて、イベントに参加申し込みをしている場合、キャンセルボタンを表示する -->
        <% if current_user && user_apply_event?(@event) %>
          <div class="text-center"><%= link_to '参加キャンセル', attend_path(@attend, event_id: @event.id),
                                            method: :delete, class: 'btn btn-danger' %></div>
        <% elsif current_user == @event.user %>
          <div></div>
        <% else %>
          <!-- ログインしていない場合、ログイン画面に遷移させる -->
          <div class="text-center"><%= link_to '参加を申し込む', attends_path(event_id: @event.id),
                                            method: :post, class: 'btn-lg btn-primary' %></div>
        <% end %>
      </div>

      <br/>
      <p>現在の参加者数：<%= @guests.count %>人</p>
      <% @guests.each do |g| %>
        <p><%= g.name %>さん</p>
      <% end %>
      <%= link_to '参加者一覧', guests_index_event_path(@event) %>

      <%= link_to '一覧へ', events_path, class: 'btn btn-primary' %>

      <!-- イベントの投稿者がログインしている時のみ編集、削除ボタンを表示する -->
      <% if current_user && user_contribute_event?(@event) %>
        <%= link_to '編集', edit_event_path(@event), class: 'btn btn-success' %>
        <%= link_to '削除', event_path(@event),
                            method: :delete,
                            data: { confirm: "タスク「#{@event.name}」を削除します。よろしいですか？" },
                            class: 'btn btn-danger' %>
      <% end %>
    </div>
  </div>
</div>